import{useEffect,useState,type ReactNode}from'react'
import{getSystemInfo,type SystemInfo}from'./api'
type Page='setup'|'login'|'home'|'settings'
const getPage=():Page=>{const value=window.location.pathname.slice(1);return value==='setup'||value==='login'||value==='settings'?value:'home'}
export function App(){
 const[page,setPage]=useState<Page>(getPage),[info,setInfo]=useState<SystemInfo|null>(null),[error,setError]=useState<string|null>(null)
 const load=()=>{setError(null);const controller=new AbortController();getSystemInfo(controller.signal).then(setInfo).catch((reason:unknown)=>{if(!(reason instanceof DOMException&&reason.name==='AbortError'))setError(reason instanceof Error?reason.message:'Unable to connect')});return controller}
 useEffect(()=>{const controller=load();return()=>controller.abort()},[]);useEffect(()=>{const onPop=()=>setPage(getPage());addEventListener('popstate',onPop);return()=>removeEventListener('popstate',onPop)},[])
 const navigate=(next:Page)=>{history.pushState({},'',`/${next}`);setPage(next)}
 const content=page==='home'?<Home info={info} error={error} retry={load}/>:page==='settings'?<Settings info={info} error={error}/>:<Unavailable page={page}/>
 return <div className="app-shell"><aside><div className="brand"><div className="mark">V</div><span>VyNode</span></div><nav aria-label="Primary"><button className={page==='home'?'active':''} onClick={()=>navigate('home')}><span aria-hidden="true">⌂</span>Home</button><button className={page==='settings'?'active':''} onClick={()=>navigate('settings')}><span aria-hidden="true">⚙</span>Settings</button></nav><p className="phase">Phase 0 foundation</p></aside><main><header><button className="mobile-brand" onClick={()=>navigate('home')} aria-label="Go home"><span className="mark">V</span></button><div><p className="eyebrow">VYNODE MEDIA</p><h1>{page[0].toUpperCase()+page.slice(1)}</h1></div><Status online={!!info&&!error} loading={!info&&!error}/></header>{content}<nav className="mobile-nav" aria-label="Mobile navigation"><button className={page==='home'?'active':''} onClick={()=>navigate('home')}>Home</button><button className={page==='settings'?'active':''} onClick={()=>navigate('settings')}>Settings</button></nav></main></div>
}
function Status({online,loading}:{online:boolean;loading:boolean}){return <div className={`connection ${online?'online':''}`} role="status" aria-live="polite"><i/>{loading?'Connecting…':online?'Server online':'Server offline'}</div>}
function Home({info,error,retry}:{info:SystemInfo|null;error:string|null;retry:()=>unknown}){if(error)return <State title="Server unavailable" body={error}><button onClick={retry}>Try again</button></State>;if(!info)return <section className="panel loading" aria-label="Loading server information"><div/><div/><div/></section>;return <section className="content"><div className="hero"><p className="eyebrow">LOCAL SERVER</p><h2>{info.serverName}</h2><p>Your VyNode foundation is connected and ready for the next implementation phase.</p></div><dl><div><dt>Version</dt><dd>{info.version}</dd></div><div><dt>Platform</dt><dd>{info.operatingSystem} · {info.architecture}</dd></div><div><dt>Database</dt><dd>{info.databaseType}</dd></div><div><dt>Uptime</dt><dd>{formatUptime(info.uptimeSeconds)}</dd></div></dl></section>}
function Settings({info,error}:{info:SystemInfo|null;error:string|null}){return <section className="panel"><h2>Server identity</h2>{error?<p className="muted">Server details are unavailable.</p>:!info?<p className="muted">Loading server identity…</p>:<dl className="vertical"><div><dt>Server name</dt><dd>{info.serverName}</dd></div><div><dt>Installation ID</dt><dd className="mono">{info.instanceId}</dd></div><div><dt>API database</dt><dd>{info.databaseType}</dd></div></dl>}</section>}
function Unavailable({page}:{page:'setup'|'login'}){return <State title={`${page==='setup'?'Setup':'Login'} is not enabled`} body="Authentication is intentionally deferred to Phase 1. No credentials or setup actions are accepted yet."/>}
function State({title,body,children}:{title:string;body:string;children?:ReactNode}){return <section className="empty"><div className="empty-icon" aria-hidden="true">V</div><h2>{title}</h2><p>{body}</p>{children}</section>}
function formatUptime(seconds:number){if(seconds<60)return`${seconds}s`;if(seconds<3600)return`${Math.floor(seconds/60)}m`;return`${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m`}

