let access="",creating=false;const q=s=>document.querySelector(s);
async function request(path,init={}){const headers={"Content-Type":"application/json",...(init.headers||{})};if(access)headers.Authorization=`Bearer ${access}`;const response=await fetch(`/api/v1${path}`,{credentials:"include",...init,headers});if(!response.ok){const problem=await response.json().catch(()=>({}));throw new Error(problem.title||`Request failed (${response.status})`)}return response.status===204?{}:response.json()}
q("#mode").onclick=()=>{creating=!creating;q("[name=displayName]").hidden=!creating;q("#mode").textContent=creating?"Already have an account? Sign in":"Create Account";q("#auth button").textContent=creating?"Create VyNode Account":"Sign In"};
q("#auth").onsubmit=async event=>{event.preventDefault();q("#error").textContent="";const data=new FormData(event.target),body={username:data.get("username"),password:data.get("password"),displayName:data.get("displayName"),deviceName:"Web browser",platform:"WEB",clientName:"VyNode Web"};try{const value=await request(creating?"/account/register":"/account/login",{method:"POST",body:JSON.stringify(body)});access=value.accessToken;await home()}catch(error){q("#error").textContent=error.message}};
function renderServers(servers){const list=q("#servers");list.replaceChildren();for(const server of servers){const card=document.createElement("div");card.className="server";const name=document.createElement("b");name.textContent=server.name;const details=document.createElement("small");details.textContent=`${server.relationship.toLowerCase()} · ${server.lastSeenAt?`Last seen ${new Date(server.lastSeenAt).toLocaleString()}`:"Not seen yet"}`;const endpoint=(server.endpoints||[]).find(item=>item.url),open=document.createElement("button");open.textContent=endpoint?"Open server":"Server unavailable";open.disabled=!endpoint;open.onclick=async()=>{open.disabled=true;try{const value=await request(`/servers/${encodeURIComponent(server.id)}/assertion`,{method:"POST",body:"{}"}),target=new URL(endpoint.url);target.hash=new URLSearchParams({connect_assertion:value.assertion});location.assign(target.toString())}catch(error){q("#error").textContent=error.message;open.disabled=false}};card.append(name,document.createElement("br"),details,open);list.append(card)}}
async function home(){const[me,servers,devices]=await Promise.all([request("/account/me"),request("/servers"),request("/devices")]);q(".auth-card").hidden=true;q("#account").hidden=false;q("#profile").textContent=me.displayName;q("#handle").textContent=`@${me.username}`;q("#empty").hidden=servers.length>0;renderServers(servers);q("#devices").innerHTML=devices.map(device=>`<div class="device"><b>${escape(device.name)}</b><br><small>${escape(device.platform)} · ${device.current?"This device":`Last seen ${new Date(device.lastSeenAt).toLocaleString()}`}</small></div>`).join("")}
q("#device").onclick=()=>q("#code").hidden=false;q("#code").onsubmit=async event=>{event.preventDefault();await request("/device-codes/approve",{method:"POST",body:JSON.stringify({userCode:new FormData(event.target).get("userCode")})});q("#code").hidden=true};q("#deny").onclick=async()=>{await request("/device-codes/deny",{method:"POST",body:JSON.stringify({userCode:new FormData(q("#code")).get("userCode")})});q("#code").hidden=true};
const invited=new URL(location.href).searchParams.get("invite")||"";if(invited)q("#invitation [name=token]").value=invited;q("#invite").onclick=()=>q("#invitation").hidden=false;q("#invitation").onsubmit=async event=>{event.preventDefault();q("#error").textContent="";const button=q("#invitation button");button.disabled=true;try{const value=await request("/invitations/accept",{method:"POST",body:JSON.stringify({token:new FormData(event.target).get("token")})}),endpoint=(value.server.endpoints||[]).find(item=>item.url);if(!endpoint)throw new Error("Server unavailable");const target=new URL(endpoint.url);target.hash=new URLSearchParams({connect_invitation_redemption:value.redemption,connect_assertion:value.assertion});location.assign(target.toString())}catch(error){q("#error").textContent=error.message;button.disabled=false}};
q("#logout").onclick=async()=>{await request("/account/logout",{method:"POST",body:"{}"});location.reload()};function escape(value){const element=document.createElement("span");element.textContent=value;return element.innerHTML}
